version: '3.1'

services:
  sifeedback-web:
    image: sifeedback/sifeedback-web:dev
    ports:
      - "80:80"
    restart: unless-stopped
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "1qaz@WSX"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1443"
volumes: 
  registry: